version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ideaforge
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ideaforge
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://ideaforge:secret@db:5432/ideaforge
      JWT_SECRET=devsecret
      PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_BACKEND_URL=http://localhost:3000
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  db_data:
